### ISSUE TITLE
AttributeError: 'str' object has no attribute 'removesuffix'

### ISSUE THREAD

**Issue by Egida** [vP3nguin/GitShodanKey#1]
Searching for free Shodan api keys in public Github repositories.
Please keep in mind that this will take a few hours!

Traceback (most recent call last):
  File "gitshodankey.py", line 98, in <module>
    keywordList.append(l.removesuffix("\n"))
AttributeError: 'str' object has no attribute 'removesuffix'

**Comment by vP3nguin** [comment]
`removesuffix` is a python 3.9+ method in str. In previous versions, str doesn't have a `removesuffix` attribute.
Please check if python is up to date.
