### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by z0-dataleak** [vP3nguin/GitShodanKey#2]
Traceback (most recent call last):
  File "gitshodankey.py", line 98, in <module>
    keywordList.append(l.removesuffix("\n"))
AttributeError: 'str' object has no attribute 'removesuffix'

**Comment by vP3nguin** [comment]
`removesuffix` is a python 3.9+ method in str. In previous versions, str doesn't have a `removesuffix` attribute.
Please check if python is up to date.
