### ISSUE TITLE
You have exceeded a secondary rate limit

### ISSUE THREAD

**Issue by z0-dataleak** [vP3nguin/GitShodanKey#3]
OUTPUT:
08.03.2022 23:55:42 - Searching with query: 'language:python sd=shodan('
08.03.2022 23:59:07 - Searching with query: 'language:python sd=shodan.shodan('
08.03.2022 23:59:43 - Searching with query: 'language:python shodan_api_key='

Error: 403 {"documentation_url": "https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#secondary-rate-limits", "message": "You have exceeded a secondary rate limit. Please wait a few minutes before you try again."}

**Comment by vP3nguin** [comment]
No, sorry, not that I know of right now.

**Comment by z0-dataleak** [comment]
so the script wont work? does it work on your computer?

**Comment by z0-dataleak** [comment]
Perhaps the request speed can be adjusted, I'll see if I can give it a try based on your project

**Comment by vP3nguin** [comment]
I've updated the [gitshodankey.py](https://github.com/vP3nguin/GitShodanKey/blob/main/gitshodankey.py).
Optimized the way it handles the error. Now it will wait for 30 seconds and try again until the limit is released.

Try it and see if it works.

**Comment by vP3nguin** [comment]
Keep in mind that it will increase the execution time

**Comment by z0-dataleak** [comment]
Nice, it works!
