### ISSUE TITLE
Error: local variable 'tc' referenced before assignment

### ISSUE THREAD

**Issue by Mrchen157** [vP3nguin/GitShodanKey#5]
Error: local variable 'tc' referenced before assignment

**Comment by vP3nguin** [comment]
Please download the updated version of gitshodankey.py and try again.

**Comment by vP3nguin** [comment]
If it still doesn't work then let me know your complete terminal output.

**Comment by Mrchen157** [comment]
Thanks, I defined a local variable ct under the search method and it has compiled.

**Comment by Mrchen157** [comment]
It's "tc=0", I made a mistake, sorry

**Comment by vP3nguin** [comment]
I didn't know you wanted to compile it, but I committed the change so there won't be any problems in the future.
